sudo: required
services:
  - docker

before_install:
  - docker build -t matheustp/docker-angular -f Dockerfile.dev .

script:
  - docker run matheustp/docker-angular npm run test:ci

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-angular"
  env: "DockerAngular-env"
  bucket_name: "elasticbeanstalk-us-east-2-187293334717"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"