FROM node:10-stretch
RUN apt-get update \
    && apt-get install -y --no-install-recommends chromium
ENV CHROME_BIN=/usr/bin/chromium

WORKDIR /app

COPY package.json .
RUN npm install
COPY . .


CMD ["npm", "run", "start"]